[package]
name = "nix-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.5", features = ["derive"] }
eframe = "0.21.3"
catppuccin-egui = "2.0"
rfd = "0.11"